package com.bank.bian.financialstatements;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Financial Statements
 *
 * Business Area:      Business Support
 * Business Domain:    Finance
 * Functional Pattern: Process
 * Asset Type:         Financial Statement
 * Control Record:     Financial Statement Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Financial Statements — BIAN Semantic API")
                .description("Service Domain 'Financial Statements' (Process pattern) "
                        + "operating on the 'Financial Statement Procedure' control record.")
                .version("0.1.0"));
    }
}
